runtime: nodejs14

env: flex

instance_class: F1

service: todo_frontend

default_expiration: "24h"

env_variables:
  NODE_ENV: "production"

automatic_scaling:
  min_instance: 0

beta_settings:
  cloud_sql_instances: todo-320907:asia-northeast1:todo-prod=tcp:3306

handlers:
  - url: /views
    secure: always
    script: auto
  - url: /public
    secure: always
    script: auto

