runtime: nodejs

env: flex

instance_class: F1

handlers:
  - url: /stylesheets
    static_dir: stylesheets
  - url: /.*
    secure: always
    script: auto

default_expiration: "24h"

env_variables:
  NODE_ENV: "production"

automatic_scaling:
  min_instances: 0




